/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csvbookqueryII;

import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;

import com.dhl.dashboard.DashboardApplication;
import com.dhl.dashboard.repository.CsvUserRepository;

@RunWith(SpringRunner.class)
@SpringBootTest
@ContextConfiguration(classes = DashboardApplication.class)
public class CsvUserTest {
	
    @Autowired
    private CsvUserRepository csvUserRepository;
    
	/*
	 * @Test
	 * 
	 * @Transactional("apemTransactionManager") public void createCsvUser() {
	 * System.out.println("started test cases"); CsvUserModel user = new
	 * CsvUserModel(); user.setFirstName("ajay"); user.setMobileNo(543543255L);
	 * user.setEmail("test@gmail.com"); user.setPassword("PASSWORD");
	 * user.setConfirmPassword("PASSWORD"); csvUserRepository.save(user);
	 * System.out.println("completed test cases"); }
	 */
    
    @org.junit.Test
    public void sampleTest() {      
    	System.out.println("WOW !! ");
    }
}
